apiVersion: apps/v1
kind: Deployment
metadata:
  name: microtest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microtest
  template:
    metadata:
      labels:
        app: microtest
    spec:
      containers:
        - name: microtest
          image: kellybrazil/microtest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: microtest
  name: microtest
spec:
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: microtest
  sessionAffinity: None
  type: LoadBalancer